# When a PR is merged, any associated issues will have a Done label applied
# The label will depend on the issue type, see: ./github/close-label.yml
name: ðŸ’¡ Apply Done Label
on:
  pull_request:
    types: [opened, merged, closed]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: logerfo/close-label@0.0.4
      with:
        repo-token: ${{ secrets.BOT_GITHUB_TOKEN }}
