# Creates a new tag, whenever the app version (in package.json) is updated in master
# And marks any relevant issues as fixed
name: ğŸ—ï¸ Release Tag new Versions
on:
  push:
    branches:
      - master
jobs:
  tag-pre-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        strategy: package
        commit_message_template: "ğŸ”– {{number}} {{message}} (by {{author}})\nSHA: {{sha}}\n."
  mark-issue-fixed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Label Fixed Issues
      uses: gh-bot/fix-labeler@master
      with:
        token: ${{ secrets.BOT_GITHUB_TOKEN }}
        label: 'âœ… Fixed'
