# Builds and published Dashy's documentation website
name: Build Docs Site
on:
  workflow_dispatch:
  push:
    branches: [ WEBSITE/docs-site-source ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/WEBSITE/docs-site-source'
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: ./
          git-user: ${{ github.actor }}
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
