# Attempts to auto-detect weather an issue is a duplicate, and adds a comment
name: ðŸŽ¯ Issue Duplicate Check
on:
  issues:
    types: [opened, edited]
jobs:
  check-duplicate:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/potential-duplicates@v1
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          filter: ''
          exclude: '[BUG] [QUESTION] [FEEDBACK] [SHOWCASE]'
          label: 'ðŸ•¸ï¸ Potential Duplicate'
          state: all
          threshold: 0.6
          reactions: 'eyes'
          comment: >
            Potential duplicates: {{#issues}}
              - [#{{ number }}] {{ title }} ({{ accuracy }}%)
            {{/issues}}