# Generates a list of sponsors, and inserts it into specified files
# where the `<!-- sponsors --><!-- sponsors -->` tag is
name: Inserts Sponsors
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Generate Sponsors in Readme ğŸ’–
        uses: JamesIves/github-sponsors-readme-action@1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: 'README.md'
      - name: Generate Sponsors in Credits ğŸ’–
        uses: JamesIves/github-sponsors-readme-action@1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: 'docs/credits.md'
