# Applies the 'Top Issue' label to tickets with most user reactions
name: üéØ Label Top Issues
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # Run at 01:00 each day
jobs:
  labelTopIssues:
    name: Label Top Issues
    runs-on: ubuntu-latest
    steps:
    - name: Label Issues
      uses: adamzolyak/top-issues-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        TOP_NUMBER_OF_ISSUES: 10
        TOP_LABEL_NAME: "üëç Top 10 Issue!"
        TOP_LABEL_COLOR: FBCA04
