# Adds comments to PR, based on which files are modified
name: ðŸ’¡ PR Commenter
on: [ pull_request_target ]
jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: exercism/pr-commenter-action@v1.3.0
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          config-file: .github/pr-auto-comments.yml
          template-variables: |
            { "prAuthor": "${{ github.event.pull_request.user.login }}" }
