# Adds a comment to all issues & PRs that were fixed on a new release
name: ğŸ’¡ Update Issue after Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          label-template: ğŸ›©ï¸ Released {release_tag}, ğŸ”¨ Fixed
          comment-template: |
            **The fix for this issue has now been released in {release_name} âœ¨**

            If you haven't done so already, please [update your instance](https://github.com/Lissy93/dashy/blob/master/docs/management.md#updating) to `{release_tag}` or later. See {release_link} for full info.

            Feel free to reach out if you need any more support. If you are enjoying Dashy, consider [supporting the project](https://github.com/Lissy93/dashy/blob/master/docs/contributing.md#contributing).
