name: ðŸ“Š Save Repo Analytics
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
jobs:
  gen-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Analytics
        uses: jgehrcke/github-repo-stats@HEAD
        with:
          repository: lissy93/dashy
          databranch: DATA/repo-stats
          ghtoken: ${{ secrets.BOT_GITHUB_TOKEN }}